{
 "title": "Example dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "ML task monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Predicted value percentiles [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum by (job, le) (rate(prediction_histogram_bucket[5m])))",
     "legendFormat": "0.01"
    },
    {
     "expr": "histogram_quantile(0.05, sum by (job, le) (rate(prediction_histogram_bucket[5m])))",
     "legendFormat": "0.05"
    },
    {
     "expr": "histogram_quantile(0.1, sum by (job, le) (rate(prediction_histogram_bucket[5m])))",
     "legendFormat": "0.1"
    },
    {
     "expr": "histogram_quantile(0.25, sum by (job, le) (rate(prediction_histogram_bucket[5m])))",
     "legendFormat": "0.25"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(prediction_histogram_bucket[5m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (job, le) (rate(prediction_histogram_bucket[5m])))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (job, le) (rate(prediction_histogram_bucket[5m])))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(prediction_histogram_bucket[5m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(prediction_histogram_bucket[5m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Distribution of predictions [5m]",
   "type": "graph",
   "description": "Inspired by [Jeremy Jordan's example](https://github.com/jeremyjordan/ml-monitoring/blob/main/dashboards/model.json)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prediction_histogram_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average predicted value [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prediction_histogram_sum[5m])) / sum(rate(prediction_histogram_count[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Flask monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}